export const DOCUMENT_STATUSES = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  BLOCKED: 'blocked',
};

export const DOCUMENT_STATUS_LABELS = {
  [DOCUMENT_STATUSES.PENDING]: 'Pending',
  [DOCUMENT_STATUSES.APPROVED]: 'Approved',
  [DOCUMENT_STATUSES.REJECTED]: 'Rejected',
  [DOCUMENT_STATUSES.BLOCKED]: 'Blocked',
};
export const DOCUMENT_STATUS_COLORS = {
  [DOCUMENT_STATUSES.PENDING]: 'text-yellow-500',
  [DOCUMENT_STATUSES.APPROVED]: 'text-green-500',
  [DOCUMENT_STATUSES.REJECTED]: 'text-red-500',
  [DOCUMENT_STATUSES.BLOCKED]: 'text-gray-500',
} as const;

export const DOCUMENT_STATUS_OPTIONS = [
  {
    value: DOCUMENT_STATUSES.PENDING,
    label: DOCUMENT_STATUS_LABELS[DOCUMENT_STATUSES.PENDING],
    color: DOCUMENT_STATUS_COLORS[DOCUMENT_STATUSES.PENDING],
  },
  {
    value: DOCUMENT_STATUSES.APPROVED,
    label: DOCUMENT_STATUS_LABELS[DOCUMENT_STATUSES.APPROVED],
    color: DOCUMENT_STATUS_COLORS[DOCUMENT_STATUSES.APPROVED],
  },
  {
    value: DOCUMENT_STATUSES.REJECTED,
    label: DOCUMENT_STATUS_LABELS[DOCUMENT_STATUSES.REJECTED],
    color: DOCUMENT_STATUS_COLORS[DOCUMENT_STATUSES.REJECTED],
  },
  {
    value: DOCUMENT_STATUSES.BLOCKED,
    label: DOCUMENT_STATUS_LABELS[DOCUMENT_STATUSES.BLOCKED],
    color: DOCUMENT_STATUS_COLORS[DOCUMENT_STATUSES.BLOCKED],
  },
];
