export const DOCUMENT_STATUSES = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  BLOCKED: 'blocked',
};

export const DOCUMENT_STATUS_LABELS = {
  [DOCUMENT_STATUSES.PENDING]: 'Đang chờ duyệt',
  [DOCUMENT_STATUSES.APPROVED]: 'Đã duyệt',
  [DOCUMENT_STATUSES.REJECTED]: 'Bị từ chối',
  [DOCUMENT_STATUSES.BLOCKED]: 'Bị chặn',
};
export const DOCUMENT_STATUS_COLORS = {
  [DOCUMENT_STATUSES.PENDING]: '#a38e06',
  [DOCUMENT_STATUSES.APPROVED]: '#64ff70',
  [DOCUMENT_STATUSES.REJECTED]: '#d33737',
  [DOCUMENT_STATUSES.BLOCKED]: '#5d81b4',
} as const;

export const DOCUMENT_STATUS_OPTIONS = [
  {
    value: DOCUMENT_STATUSES.PENDING,
    label: DOCUMENT_STATUS_LABELS[DOCUMENT_STATUSES.PENDING],
    color: DOCUMENT_STATUS_COLORS[DOCUMENT_STATUSES.PENDING],
  },
  {
    value: DOCUMENT_STATUSES.APPROVED,
    label: DOCUMENT_STATUS_LABELS[DOCUMENT_STATUSES.APPROVED],
    color: DOCUMENT_STATUS_COLORS[DOCUMENT_STATUSES.APPROVED],
  },
  {
    value: DOCUMENT_STATUSES.REJECTED,
    label: DOCUMENT_STATUS_LABELS[DOCUMENT_STATUSES.REJECTED],
    color: DOCUMENT_STATUS_COLORS[DOCUMENT_STATUSES.REJECTED],
  },
  {
    value: DOCUMENT_STATUSES.BLOCKED,
    label: DOCUMENT_STATUS_LABELS[DOCUMENT_STATUSES.BLOCKED],
    color: DOCUMENT_STATUS_COLORS[DOCUMENT_STATUSES.BLOCKED],
  },
];
